### ISSUE TITLE
error in running example

### ISSUE THREAD

**Issue by trinayan** [acbull/pyHGT#12]
Thanks for your great work. I try to run the example train_paper_field.py and get this error. Do I need to move files around before running the script?

 "Traceback (most recent call last):
  File "train_paper_field.py", line 2, in <module>
    from .data import *
ImportError: attempted relative import with no known parent package

**Comment by acbull** [comment]
Sorry, after changing the file structure, the relative location of data is now within pyHGT.data. I'll fix the bug asap and let you know.

**Comment by acbull** [comment]
Hi, I've fixed the directory error, and it work well on my side. Can you try again and see if there is any other problems?

**Comment by trinayan** [comment]
Hi. I tried running this example and got another error "

python3 train_paper_field.py --data_dir /home/trinayan/GNN_Bench/HeterogeneousGraphs/pyHGT/OAG/ --domain _NN --conv_name hgt
Data Preparation: 39.2s
Traceback (most recent call last):
  File "train_paper_field.py", line 243, in <module>
    edge_time.to(device), edge_index.to(device), edge_type.to(device))
  File "/home/trinayan/GNN_Bench/HeterogeneousGraphs/pyHGT/OAG/pyHGT/model.py", line 79, in forward
    meta_xs = gc(meta_xs, node_type, edge_index, edge_type, edge_time)
  File "/home/trinayan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/trinayan/GNN_Bench/HeterogeneousGraphs/pyHGT/OAG/pyHGT/conv.py", line 317, in forward
    return self.base_conv(meta_xs, node_type, edge_index, edge_type, edge_time)
  File "/home/trinayan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/trinayan/GNN_Bench/HeterogeneousGraphs/pyHGT/OAG/pyHGT/conv.py", line 58, in forward
    edge_type=edge_type, edge_time = edge_time)
  File "/home/trinayan/.local/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 233, in propagate
    kwargs)
  File "/home/trinayan/.local/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 156, in __collect__
    self.__set_size__(size, dim, data)
  File "/home/trinayan/.local/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 119, in __set_size__
    elif the_size != src.size(self.node_dim):
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got -2)".

Do you know what can be the issue?. Is my command correct?. Thanks for taking the time to help.

**Comment by acbull** [comment]
Which pyG version are you using? As is shown in the requirement.py, we are using:

pytorch_geometric 1.3.2
torch-cluster==1.4.5
torch-scatter==1.3.2
torch-sparse==0.4.3

**Comment by trinayan** [comment]
Got it . I was under the assumption that newer versions would work fine. but it seems this was the problem. now it works . thanks for the help
