### ISSUE TITLE
IndexError about result

### ISSUE THREAD

**Issue by githublx1997** [acbull/pyHGT#37]
Traceback (most recent call last):
  File "train_paper_field.py", line 242, in <module>
    node_rep = gnn.forward(node_feature.to(device), node_type.to(device), edge_time.to(device), edge_index.to(device), edge_type.to(device))
  File "/home/liangxiao/pyHGT/OAG/pyHGT/model.py", line 79, in forward
    meta_xs = gc(meta_xs, node_type, edge_index, edge_type, edge_time)
  File "/home/liangxiao/anaconda3/envs/pyhgt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/liangxiao/pyHGT/OAG/pyHGT/conv.py", line 317, in forward
    return self.base_conv(meta_xs, node_type, edge_index, edge_type, edge_time)
  File "/home/liangxiao/anaconda3/envs/pyhgt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/liangxiao/pyHGT/OAG/pyHGT/conv.py", line 58, in forward
    edge_type=edge_type, edge_time = edge_time)
  File "/home/liangxiao/anaconda3/envs/pyhgt/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 234, in propagate
    kwargs)
  File "/home/liangxiao/anaconda3/envs/pyhgt/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 156, in __collect__
    self.__set_size__(size, dim, data)
  File "/home/liangxiao/anaconda3/envs/pyhgt/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 118, in __set_size__
    size[dim] = src.size(self.node_dim)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got -2)

why do I have this error ? Is there anything wrong with my pyg version or anything else?(I use the new version)

**Comment by githublx1997** [comment]
I have solved this problem by changing the pyg version to 1.4.3，it seems the _scatter had been overwritting after 1.4.3 version

**Comment by Juicechen95** [comment]
I also meet this problem. Unfortunately, I can not change pyg version to 1.4.3 for some reason. Is there any other idea to solve this problem? For example , how should I change the code to fit the higher pyg version?

**Comment by rainman503** [comment]
> I have solved this problem by changing the pyg version to 1.4.3，it seems the _scatter had been overwritting after 1.4.3 version

Do you mean the version of  pytorch-geometric?
