### ISSUE TITLE
execute author disambiguation task fail 

### ISSUE THREAD

**Issue by MandyWang666** [acbull/pyHGT#64]
I follow the Readme file ,download the preproccessed data graph_CS.pk file and run the command 'python train_author_disambiguation.py' successfully.However , console reports as follows:

Traceback (most recent call last):
  File "C:\Users\wmmsl\Documents\DDI\pyHGT\OAG\train_author_disambiguation.py", line 72, in <module>
    graph = renamed_load(open(args.data_dir + '/graph%s.pk' % args.domain, 'rb'))
  File "C:\Users\wmmsl\Documents\DDI\pyHGT\OAG\pyHGT\data.py", line 269, in renamed_load
    return RenameUnpickler(file_obj).load()
  File "C:\Users\wmmsl\miniconda3\lib\site-packages\dill\_dill.py", line 525, in load
    obj = StockUnpickler.load(self)
TypeError: an integer is required (got type bytes)

it seems that data.py can not load the .pk file and why it has to be renamed?May I know why and how to solve this issue?Thanks.

**Comment by shairal1** [comment]
Hi , I  am facing same issue , were you able to solve it ? (i have same dill version)
